<section class="categories-list-page light-grey" style="margin-bottom: 609px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">

                <div class="col-md-8 col-sm-12 col-xs-12 nopadding">

                    <div id="cartTable">
                        <?php
                        //var_dump($cartDetails->count()); exit;

                        $cartCount = $cartDetails->count();
                        $totalAmount = 0;
                        foreach ($cartDetails as $cart) {
                            //var_dump($cart); exit;
                            $brackets = "";
                            if ($cart['optionTitle'] != "" || $cart['optionTitle'] != "&nbsp;") {
                                $brackets = "( " . $cart['optionTitle'] . " )";

                            }

                            ?>

                            <!-- <tr class="cartTableRow"><td class="cartTableCell">  <span style="margin-left: 1em;"><?php echo $cart['serviceTitle'] . " " . $brackets ?> </span></td> <td class="cartTableCell"> <?php echo $cart['price'] ?> </td></td><td class="cartTableCell">
                                    <span style="color: red"><a href="#" data-optiondata ="<?php echo $cart['serviceOptionId'] ?>-#-<?php echo $cart['optionTitle'] ?>-#-<?php echo $cart['serviceId'] ?>" onclick="removePackage(this)" data-price='<?php echo $cart['price'] ?>' >X

                                        </a></span></td></tr>

                                        -->


                            <div class="serviceItem">
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <div class="blog-post">

                                        <div class="col-md-8 col-sm-8 col-xs-8">
                                            <h3 class="post-title">
                                                <a href="<?
                                                $this->url("service", array("id" => $cart['serviceId'])) ?>">
                                                    <?php echo $cart['serviceTitle'] . " " . $brackets ?>
                                                </a>
                                            </h3>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <h3 class="post-title">

                                                <?php echo $cart['price'] ?>

                                            </h3>
                                        </div>
                                        <div class="col-md-1 col-sm-1 col-xs-1">
                                            <h4 style="color: #333">
                                            <span style="color: red">
                                                <a href="#"
                                                   data-optiondata="<?php echo $cart['serviceOptionId'] ?>-#-<?php echo $cart['optionTitle'] ?>-#-<?php echo $cart['serviceId'] ?>"
                                                   onclick="removePackage(this)"
                                                   data-price='<?php echo $cart['price'] ?>'>X

                                        </a></span>

                                            </h4>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <?php
                            $totalAmount = $totalAmount + $cart['price'];

                        }

                        ?>
                    </div> <!---cart table ends here-->


                    <div id="emptyCart" style="display:<?php echo ($cartCount == 0) ? "block" : "none"; ?>">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="blog-post">

                                <div class="col-md-8 col-sm-8 col-xs-8">
                                    <h3 class="post-title">
                                        Your Cart is Empty
                                    </h3>
                                </div>

                            </div>
                        </div>
                    </div>



                    <form id="checkoutForm" method="post" action="<?php echo $this->url("cart", array("action" => "process")) ?>"
                          style="display:<?php echo ($cartCount == 0) ? "none" : "block"; ?>">
                        <div class="item" id="totalAmt">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="blog-post" style="background-color: #333; color: #fff">

                                    <div class="col-md-3 col-sm-3 col-xs-3">
                                        <h3 class="post-title">
                                            <a href="#">
                                                Total
                                            </a>
                                        </h3>
                                    </div>
                                    <div class="col-md-5 col-sm-5 col-xs-5">
                                        <h3 class="post-title">

                                            <input type="hidden" name="amount" value="<?php echo $totalAmount; ?>"
                                                   id="totalAmountForm">
                                            <input type="hidden" name="gateway" value="paytm">

                                            <span style="margin-left: -1em;"
                                                  id="totalAmount"><?php echo $totalAmount; ?></span>

                                        </h3>
                                    </div>

                                    <div class="col-md-3 col-sm-3 col-xs-3">
                                        <button class="btn btn-success " type="submit" id="proceed">Proceed to
                                            checkout
                                        </button>
                                    </div>

                                </div>
                            </div>
                        </div>


                    </form>


                </div>


                <div class="col-md-4 col-sm-12 col-xs-12">
                    <aside>
                        <?php
                        foreach ($serviceOptions as $serviceOption => $so1) {
                            ?>

                            <div class="widget">

                                <div class="widget-heading"><span class="title"> <?php echo $serviceOption ?></span>
                                </div>
                                <ul>
                                    <?php foreach ($so1 as $service) {
                                        $optionData = $service['serviceOptionId'] . "-#-" . $service['optionTitle'] . "-#-" . $service['serviceId'] . "-#-" . $serviceOption;
                                        ?>

                                        <li style="padding: 0.5em;">

                                            <span> <a href="<?php echo $this->url("service", array("id" => $service['serviceId'])) ?>"> <?php echo $service['optionTitle']; ?>
                                                    ( Rs. <?php echo $service['price']; ?>)</a> </span>
                                            <span style="margin-left: 2em;">
                                                <button title="Add to Cart" type="button" class="btn btn-xs btn-primary"
                                                        data-optiondata="<?php echo $optionData ?>"
                                                        value="<?php echo $service['price'] ?>"
                                                        onclick="return addtoCart(this)">( + )</button></span>

                                        </li>


                                    <?php } ?>
                                </ul>


                            </div>


                            <?php
                        } ?>


                </div>


                </aside>
            </div>
        </div>
    </div>
    </div>
</section>

