<section class="categories-list-page light-grey" style="margin-bottom: 609px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">

                <div class="col-md-12 col-sm-12 col-xs-12 nopadding">

                    <div id="cartTable">
                        <div class="serviceItem">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="blog-post">



                        <form action="<?php if ($gateway == "paytm") {
                            echo PAYTM_TXN_URL;
                        } else {
                            echo "";
                        } ?>" id="paymentForm" method="post">
                            <?php
                            if ($gateway == "razorpay") {
                                ?>

                                <input type="hidden" id="custname" name="custname"
                                       value="<?php echo $params['name'] ?>">
                                <input type="hidden" id="custemail" name="custemail"
                                       value="<?php echo $params['email'] ?>">
                                <input type="hidden" id="amount" name="amount" value="<?php echo $params['amount'] ?>">
                                <input type="hidden" id="mobile" name="mobile" value="<?php echo $params['mobile'] ?>">

                                <?php
                            }
                            ?>
                            <?php
                            if ($gateway == "paytm") {
                                ?>


                                <?php
                                foreach ($params as $param => $val) {
                                    //var_dump($param); exit;
                                    ?>
                                    <input type="hidden" name="<?php echo $param ?>" value="<?php echo $val ?>">

                                    <?php
                                }

                            }
                            ?>

                            <H1 id="paymentStatus" style="padding: 100px 20px 100px 20px "> PLEASE WAIT WHILE WE PROCESS
                                YOUR PAYMENT ...... </H1>



                        </form>
                                </div>
                            </div>
                        </div>

                    </div>
                    <br><br>

                </div>
            </div>
        </div>


    </div>
</section>
    <!-- /Content Center -->

    <!-- Content Right
    <div class="content-right">
        <div class="block background" id="social-like">
            <h2 class="title-1">Share Us With Your Friends</h2>
            <div class="block-content">
                <div class="social-like linkedin"><a href="#" class="like-button">LinkedIn</a><span class="count">500</span></div>
                <div class="social-like motibu"><a href="#" class="like-button">Motibu</a><span class="count">2.7K</span></div>
                <div class="social-like facebook"><a href="#" class="like-button">Facebook</a><span class="count">1.3K</span></div>
                <div class="social-like twitter"><a href="#" class="like-button">Twitter</a><span class="count">868</span></div>
            </div>
        </div>
        <div class="block border" id="advertising">
            <div class="block-content"> <img alt="sidebarad" src="images/sb-ad.jpg">
                <!-- <div class="advertising-test">300x250<br/>
                  Ad Banner</div>-->
    </div>
    </div>


    </div>
    <!-- /Content Right -->

    <div class="clear"></div>

    <!-- Clear Line -->

    </div>


    </div>
    </div>

    <?php
    if ($gateway == "razorpay") {
        ?>

        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>

        <script>
            $(document).ready(function () {

                //  $("#paymentForm").submit(function(){

                var amount = $("#amount").val() * 100;
                var mobile = $("#mobile").val();
                var options = {
                    "key": "rzp_live_PrW4PBBZe317iE",
                    "amount": amount,
                    "contact": mobile,
                    "name": "JobstoNaukri",
                    "description": $("#description").val(),
                    //"image": "",
                    "handler": function (response) {
                        alert("Your Payment is sucessful");
                        console.log(response);
                    },
                    "prefill": {
                        "name": $("#custname").val(),
                        "email": $("#custemail").val()
                    },
                    "notes": {
                        // "address": $("#address").val()
                    },
                    "theme": {
                        "color": "#F37254"
                    }
                };
                var rzp1 = new Razorpay(options);
                rzp1.open();

                $("#makePayment").trigger("click", function (e) {
                    rzp1.open();
                    e.preventDefault();
                });

                //      return false;

                //  });

            })

        </script>
        <?php
    }

    if ($gateway == "paytm"){
    ?>
    <script>

        //$("#paymentForm").submit();
        document.getElementById('paymentForm').submit();

    </script>
<?php
}
?>