<section class="categories-list-page light-grey" style="margin-bottom: 609px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">

                <div class="col-md-12 col-sm-12 col-xs-12 nopadding">

                    <div id="cartTable">






                    <div id="emptyCart" >>
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="blog-post">

                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <h1 class="post-title">
                                        <?php
                                        //; var_dump($res);
                                        $msg = "";
                                        if($res["STATUS"]=="TXN_SUCCESS"){
                                            $msg == "Thanks for your payment <br> Your Order ID is :".$res['ORDERID'];
                                        } else {
                                            $msg = $res["RESPMSG"];
                                        }
                                        ?>

                                        <H1 id="paymentStatus" style="padding: 100px 20px 100px 20px "> <?php echo $msg ?> </H1>
                                    </h1>
                                </div>

                            </div>
                        </div>
                    </div>






                </div>





            </div>
        </div>
    </div>
    </div>
</section>

