<section class="job-breadcrumb">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-7 co-xs-12 text-left">
                <h3>Login Page</h3>
            </div>
            <div class="col-md-6 col-sm-5 co-xs-12 text-right">
                <div class="bread">
                    <ol class="breadcrumb">
                        <li><a href="#">Home</a> </li>
                        <li class="active">login</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="login-page light-blue" style="margin-bottom: 609px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="login-container">
                    <div class="loginbox">
                        <form method="post" action="<?php echo $this->url("register",array("action"=>"login"));?>">
                       <!-- <div class="loginbox-title">sign in using social accounts</div>
                        <ul class="social-network social-circle onwhite">
                            <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#" class="icoLinkedin" title="Linkedin +"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                        <div class="loginbox-or">
                            <div class="or-line"></div>
                            <div class="or">OR</div>
                        </div> -->

                            <?php

                            if(isset($status)){
                                //var_dump($status);
                                ?>
                                <div class="form-group">
                                    <div role="alert" class="alert <?php echo ($result=="success")?"alert-success":"alert-danger"?> alert-dismissible">
                                        <button aria-label="Close" data-dismiss="alert" class="close" type="button"><span aria-hidden="true">×</span></button>
                                        <strong>
                                            <?php

                                            if ($status == "fail") {
                                                echo $message;
                                            }




                                            ?>

                                        </strong>
                                    </div>
                                </div>
                                <?php
                            }
                            ?>
                        <div class="form-group">
                            <label>Email: <span class="required">*</span></label>
                            <input placeholder="" class="form-control" type="email" name="email">
                        </div>
                        <div class="form-group">
                            <label>Password: <span class="required">*</span></label>
                            <input placeholder="" class="form-control" type="password" name="passwd">
                        </div>
                        <div class="loginbox-forgot">
                            <a href="">Forgot Password?</a>
                        </div>
                        <div class="loginbox-submit">
                            <input class="btn btn-default btn-block" value="Login" type="submit">
                        </div>

                        </form>

                            <div class="loginbox-signup">
                            <a href="<?php echo $this->url("register",array("action"=>"index")) ?>">Sign Up With Email</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>