<section class="contact-us light-grey" style="margin-bottom: 609px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="Heading-title black">
                        <h1>Payment Details</h1>
                        <p>Easy Payment to make you get going without  registering </p>
                    </div>
                </div>
                <div class="col-md-8 col-sm-8 col-xs-12">
                    <form class="row" method="post" action="<?php echo $this->url("payment",array("controller"=>"payment","action"=>"process"))?>">
                        <div class="col-md-12 col-sm-12">
                            <div class="form-group">
                                <label>First Name <span class="required">*</span></label>
                                <input placeholder="" class="form-control" type="text" name="name">
                            </div>
                        </div>

                        <div class="col-md-6 col-sm-12">
                            <div class="form-group">
                                <label>Last Name <span class="required">*</span></label>
                                <input placeholder="" class="form-control" type="text" name="lname">
                            </div>
                        </div>

                        <div class="col-md-6 col-sm-12">
                            <div class="form-group">
                                <label>Email <span class="required">*</span></label>
                                <input placeholder="" class="form-control" type="email" name="email">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <div class="form-group">
                                <label>Mobile <span class="required">*</span></label>
                                <input placeholder="" class="form-control" type="text" name="mobile">
                            </div>
                        </div>

                        <div class="col-md-12 col-sm-12">
                            <div class="form-group">
                                <label>Address <span class="required">*</span></label>
                                <input placeholder="" class="form-control" type="text" name="address">
                            </div>
                        </div>


                        <div class="col-md-6 col-sm-12">
                            <div class="form-group">
                                <label>City <span class="required">*</span></label>
                                <input placeholder="" class="form-control" type="text" name="city">
                            </div>
                        </div>

                        <div class="col-md-6 col-sm-12">
                            <div class="form-group">
                                <label>State <span class="required">*</span></label>
                                <input placeholder="" class="form-control" type="text" name="state">
                            </div>
                        </div>

                        <div class="col-md-6 col-sm-12">
                            <div class="form-group">
                                <label>Country <span class="required">*</span></label>
                                <input placeholder="" class="form-control" type="text" name="country">
                            </div>
                        </div>

                        <div class="col-md-6 col-sm-12">
                            <div class="form-group">
                                <label>Amount <span class="required">*</span></label>
                                <input placeholder="" class="form-control" type="text" name="amount">
                            </div>
                        </div>

                        <div class="col-md-12 col-sm-12">
                            <button type="submit" class="btn btn-default"> Proceed To Payment <i class="fa fa-angle-right"></i> </button>
                        </div>
                    </form>
                </div>
                <div class="col-md-4 col-sm-4 col-xs-12">
                    <div class="contact_block">
                        <h4>Contact Information</h4>
                        <ul class="personal-info">
                            <!--<li><i class="fa fa-map-marker"></i> 3rd Floor,Link Arcade Model Town, BBL, USA.</li>-->
                            <li><i class="fa fa-envelope"></i> Support@domain.com</li>
                            <!--<li><i class="fa fa-phone"></i> (0092)+ 124 45 78 678 </li> -->
                            <li><i class="fa fa-clock-o"></i> Mon - Sun: 8:00 - 16:00</li>
                        </ul>
                       <!-- <ul class="social-network social-circle">
                            <li><a href="contactus.html#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="contactus.html#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="contactus.html#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="contactus.html#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                        </ul> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>