<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Sales
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> All Sales
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->



<div class="row">
    <div class="col-lg-12 col-md-6">

        <form role="form" method="post" id="confirmPaymentForm" action="<?php echo  $this->url("sales",array("controller"=>"index","action"=>"confirm")) ?>">

            <div class="col-lg-10">

                <div class="form-group">
                    <label>Employee Name</label>
                    <input class="form-control" type="text" placeholder="Employee Name " name="empName">
                </div>
                <div class="form-group">
                    <label>Employee Email</label>
                    <input class="form-control" type="text" placeholder="Employee Email " name="empEmail">
                </div>

                <div class="form-group">
                    <label>Employee Mobile</label>
                    <input class="form-control" type="text" placeholder="Employee Name " name="empMobile">
                </div>

                <div class="form-group">
                    <label>Salary</label>
                    <input class="form-control" type="text" placeholder="Amount " name="salary">
                </div>

                <div class="form-group">
                    <label>Team Role</label>
                    <select class="form-control" name="role"  id="role">
                        <option value=""> Select Role</option>
                        <?php
                         foreach ($roles as $role){
                             ?>
                             <option value="<?php echo $role['id']?>"> <?php echo $role['roleName']?></option>
                        <?php
                         }
                        ?>

                    </select>


                </div>

                <div class="form-group">
                    <label>Team Leader</label>
                    <select class="form-control" name="parent" multiple="multiple" id="parent">
                        <option value=""> Select Services</option>
                        <?php
                       // foreach ()
                        ?>

                    </select>


                </div>

                <div class="form-group">
                    <label>Agent</label>
                    <input class="form-control" type="text" placeholder="Amount " name="Agent">
                </div>





            </div>



        </form>


    </div>



</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Sale Search List </h3>
            </div>


            <div class="table-responsive">
                <table class="table table-bordered table-hover table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Mobile</th>
                        <th>Date Time </th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php
                    // if($result->count() > 0) {
                    foreach ($result as $res) {
                        var_dump($res); exit;
                        ?>

                        <tr class="active">
                            <td>Atul Walkar</td>
                            <td>shrawan.walkar@gmail.com</td>
                            <td>99225515752 9595674545</td>
                            <td>29/07/2016 <br>30/07/2016</td>
                            <td>Active</td>
                        </tr>


                        <?php
                    }
                    // } else
                    {
                        ?>

                        <tr class="active">
                            <td colspan="5">Nothing Found</td>

                        </tr>

                        <?php
                    }

                    ?>


                    </tbody>
                </table>



            </div>
        </div>
    </div>
    <!-- /.row -->

