<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Employee
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> Add Employee
            </li>
            <?php
            if(isset($result)){
                if($result=="success"){
                    ?>
                    <div class="alert alert-success">
                        <strong>Success!</strong> Employee Sucessfully Added
                    </div>

                    <?php
                }
                if($result=="fail"){
                    ?>
                    <div class="alert alert-danger">
                        <strong>Error!</strong>
                        <?php echo (isset($error))? $error : "Something went wrong Try again"?>
                    </div>
                    <?php
                }
                ?>

            <?php
            }
            ?>
        </ol>
    </div>
</div>
<!-- /.row -->



<div class="row">
    <div class="col-lg-12 col-md-6">

        <form role="form" method="post" id="confirmPaymentForm" action="<?php echo  $this->url("emp",array("controller"=>"emp","action"=>"add")) ?>">

            <div class="col-lg-10">

                <div class="form-group">
                    <label>Employee Name</label>
                    <input class="form-control" type="text" placeholder="Employee Name " name="empName">
                </div>
                <div class="form-group">
                    <label>Employee Email</label>
                    <input class="form-control" type="text" placeholder="Employee Email " name="empEmail">
                </div>

                <div class="form-group">
                    <label>Employee Mobile</label>
                    <input class="form-control" type="text" placeholder="Employee Name " name="empMobile">
                </div>

                <div class="form-group">
                    <label>Target</label>
                    <input class="form-control" type="text" placeholder="Employee Target " name="target">
                </div>


                <div class="form-group">
                    <label>Salary</label>
                    <input class="form-control" type="text" placeholder="Salary" name="salary">
                </div>

                <div class="form-group" >
                    <label>Team Role</label>
                    <select class="form-control" name="role"  id="role">
                        <option value=""> Select Role</option>
                        <?php
                         foreach ($roles as $role){
                             //var_dump($role); exit;
                             ?>
                             <option value="<?php echo $role['id']?>"> <?php echo $role['name']?></option>
                        <?php
                         }
                        ?>

                    </select>


                </div>

                <div class="form-group" id="tldiv">
                    <label>Team Leader</label>
                    <select class="form-control" name="parent" id="parent">
                        <option value=""> Select Team Leader</option>
                        <?php
                        foreach ($tl as $leader){
                            ?>
                            <option value="<?php echo $leader['id']?>"> <?php echo $leader['name']?></option>
                        <?php
                        }
                        ?>

                    </select>


                </div>

                <div class="form-group">
                    <input type="submit" value="Add Employee" class="btn btn-primary">
                </div>





            </div>



        </form>


    </div>



</div>
<!-- /.row -->

