<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Employees
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> All Employees
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->



<div class="row">
    <div class="col-lg-12 col-md-6">

            <form role="form" method="post" id="confirmPaymentForm" action="<?php echo  $this->url("emp",array("controller"=>"index","action"=>"search")) ?>">

                <div class="col-lg-3">

                    <div class="form-group">
                        <label>Employee Email</label>
                        <input class="form-control" type="text" placeholder="Employee Email" name="email">
                    </div>
                </div>

                <div class="col-lg-3">

                    <div class="form-group">
                        <label>Employee Mobile</label>
                        <input class="form-control" type="text" placeholder="Employee Mobile" id="mobile">

                    </div>
                </div>


                <div class="col-lg-3">

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary" style="margin-top:25px; margin-left: 25px; width:18em ;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Search&nbsp;&nbsp;&nbsp;&nbsp;</button>

                    </div>
                </div>

                <div class="col-lg-3">

                    <div class="form-group">
                        <a href="<?php echo $this->url('emp',array("controller"=>"emp","action"=>"add"))?>" type="button" class="btn btn-success" style="margin-top:25px; margin-left: 25px; width:18em ;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Add Employee&nbsp;&nbsp;&nbsp;</a>

                    </div>
                </div>

            </form>


    </div>



</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Employees </h3>
            </div>


                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                        <tr>
                            <th>Customer Name</th>
                            <th>Role</th>
                            <th>Target</th>
                            <th>Salary </th>

                        </tr>
                        </thead>
                        <tbody>

                        <?php
                       /// echo "kkk";
                       // if($result->count() > 0) {
                            foreach ($paging as $emp) {
                               // var_dump($emp); exit;
                                ?>

                                <tr class="">
                                    <td><?php echo ucfirst($emp->name)?></td>
                                    <td><?php
                                        if($emp->roleId == 1) {
                                         echo "Agent";
                                        }
                                        if($emp->roleId == 2) {
                                            echo "Team Leader";
                                        }
                                        if($emp->roleId == 3) {
                                            echo "Upseller";
                                        }
                                        if($emp->roleId == 4) {
                                            echo "Admin";
                                        }

                                        ?></td>
                                    <td><?php echo ucfirst($emp->target)?></td>
                                    <td><?php echo ucfirst($emp->salary)?></td>

                                </tr>


                                <?php

                        }
                        ?>



                        </tbody>
                    </table>



        </div>
    </div>
</div>
<!-- /.row -->

