

<!-- JAVASCRIPT JS  -->
<script type="text/javascript" src="<?php echo $this->basepath('js/jquery-3.1.1.min.js') ?>></script>

<!-- JAVASCRIPT JS  -->
<script type="text/javascript" src="<?php echo $this->basepath('js/jquery-migrate-1.2.1.min.js') ?>></script>

<!-- BOOTSTRAP CORE JS -->
<script type="text/javascript" src="<?php echo $this->basepath('js/bootstrap.min.js') ?>></script>

<!-- JQUERY SELECT -->
<script type="text/javascript" src="<?php echo $this->basepath('js/select2.min.js') ?>></script>

<!-- MEGA MENU -->
<script type="text/javascript" src="<?php echo $this->basepath('js/mega_menu.min.js') ?>></script>



<!-- JQUERY COUNTERUP -->
<script type="text/javascript" src="<?php echo $this->basepath('js/counterup.js') ?>></script>

<!-- JQUERY WAYPOINT -->
<script type="text/javascript" src="<?php echo $this->basepath('js/waypoints.min.js') ?>></script>

<!-- JQUERY REVEAL -->
<script type="text/javascript" src="<?php echo $this->basepath('js/footer-reveal.min.js') ?>></script>

<!-- Owl Carousel -->
<script type="text/javascript" src="<?php echo $this->basepath('js/owl-carousel.js') ?>></script>

<!-- CORE JS -->
<script type="text/javascript" src="<?php echo $this->basepath('js/custom.js') ?>></script>