

<!-- JAVASCRIPT JS  -->
<script type="text/javascript" src="js/jquery-3.1.1.min.js"></script>

<!-- JAVASCRIPT JS  -->
<script type="text/javascript" src="js/jquery-migrate-1.2.1.min.js"></script>

<!-- BOOTSTRAP CORE JS -->
<script type="text/javascript" src="js/bootstrap.min.js"></script>

<!-- JQUERY SELECT -->
<script type="text/javascript" src="js/select2.min.js"></script>

<!-- MEGA MENU -->
<script type="text/javascript" src="js/mega_menu.min.js"></script>



<!-- JQUERY COUNTERUP -->
<script type="text/javascript" src="js/counterup.js"></script>

<!-- JQUERY WAYPOINT -->
<script type="text/javascript" src="js/waypoints.min.js"></script>

<!-- JQUERY REVEAL -->
<script type="text/javascript" src="js/footer-reveal.min.js"></script>

<!-- Owl Carousel -->
<script type="text/javascript" src="js/owl-carousel.js"></script>

<!-- CORE JS -->
<script type="text/javascript" src="js/custom.js"></script>