<section class="about-us">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 nopadding">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="Heading-title-left black small-heading">
                        <h3><?php echo $page->pageTitle?></h3>
                    </div>
                    <?php echo $page->content; ?>
                </div>

            </div>
        </div>
    </div>
</section>