<section class="about-us">

    <?php  $serviceDet = $service->current();?>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="Heading-title black ">
                        <h1><?php echo $serviceDet['serviceTitle']; ?> </h1>
                    </div>
                </div>
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <p>
                    <?php echo $serviceDet['content']?>
                    </p>
                    <!--<blockquote>Lorem ipsum dolor sit amet, adipisicing elit. Veritatis maxime, perferendis nostrum. Repellat nobis aperiam rerum in modi... !</blockquote>=-->
                </div>


                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="panel-group drop-accordion" id="accordion" role="tablist" aria-multiselectable="true">
                        <div class="panel panel-default">
                            <div class="panel-heading tab-collapsed" role="tab" id="headingOne">
                                <h4 class="panel-title">
                                    <a class="collapse-controle" data-toggle="collapse" data-parent="#accordion" href="aboutus3.html#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                        <?php echo $serviceDet['serviceTitle'];?>
                                        <span class="expand-icon-wrap"><i class="fa expand-icon"></i></span>
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne" aria-expanded="true">
                                <form id="resform"  method="post" action="<?php echo $this->url('cart',array("action"=>"add"))?>" onsubmit="return false">
                                    <input type="hidden" name="serviceId" id="serviceId" value="<?php echo $serviceDet['serviceId']?>">

                                    <li>
                                        <label style="margin: auto;">
                                            <input style="display: block !important; float: left" type="radio"
                                                   name="price" data-optiondata="<?php echo $serviceDet['serviceOptionId'] ?>-#-<?php echo $serviceDet['optionTitle'] ?>"
                                                   value="<?php echo $serviceDet['price'] ?>">
                                            <span style="margin-left: 10px;">For <?php echo $serviceDet['optionTitle']?> Rs <?php echo $serviceDet['price']?> </span>
                                        </label>
                                    </li>
                                    <?php
                                    //var_dump($service);
                                    //echo $service->count(); exit;
                                    if($service->count() >= 1 ) {
                                        foreach ($service as $ser) {
                                            //  var_dump($ser); exit;
                                            //    echo $ser['optionTitle'];
                                            ?>
                                            <li>
                                                <label style="margin: auto;">
                                                    <input style="display: block !important; float: left" type="radio"
                                                           name="price" data-optiondata="<?php echo $ser['serviceOptionId'] ?>-#-<?php echo $ser['optionTitle'] ?>"
                                                           value="<?php echo $ser['price'] ?>">
                                                    <span style="margin: 10px;"> <?php echo $ser['optionTitle'] ?>
                                                        Rs <?php echo $ser['price'] ?></span>
                                                </label>
                                            </li>
                                            <?php
                                        }

                                    } else {
                                        $ser = $serviceDet;
                                        ?>
                                        <li>
                                            <label style="margin: auto;">
                                                <input style="display: block !important; float: left" type="radio"
                                                       name="price" data-optiondata="<?php echo $ser['serviceOptionId'] ?>-#-<?php echo $ser['optionTitle'] ?>"
                                                       value="<?php echo $ser['price'] ?>">
                                                <!--<span style="margin-left: 10px;">For <?php echo $ser['optionTitle'] ?>
                                                Rs <?php echo $ser['price'] ?></span>-->
                                            </label>
                                        </li>


                                        <?php
                                    }
                                    ?>
                                    <li> <button style="margin: 10px" type="submit" value="Add to Cart" class="btn btn-primary" id="addToCart"> Add to Cart </button> </li>

                                </form>


                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingTwo">
                                <h4 class="panel-title">
                                    <a class="collapse-controle collapsed" data-toggle="collapse" data-parent="#accordion" href="aboutus3.html#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                        Other Services
                                        <span class="expand-icon-wrap"><i class="fa expand-icon"></i></span>
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo" aria-expanded="false">
                                <div class="panel-body">

                                    <ul>
                                        <?php
                                        foreach($all as $ser){
                                            //var_dump($ser);
                                            ?>
                                            <li><a href="<?php echo $this->url('service',array("id"=>$ser['serviceId']))?>"><?php echo $ser['serviceTitle']?></a></li>
                                            <?php
                                        }
                                        ?>


                                    </ul>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>


            </div>
        </div>
    </div>
</section>

