<?php
//echo $bread; exit;

if($bread=="true") {
    ?>
    <section class="job-breadcrumb">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-7 co-xs-12 text-left">

                    <h3><?php echo (isset($this->serviceName))? $this->serviceName : $controllerName;?></h3>
                </div>
                <div class="col-md-6 col-sm-5 co-xs-12 text-right">
                    <div class="bread">
                        <ol class="breadcrumb">
                            <li><a href="<?php echo $this->url("index")?>">Home</a></li>
                            <li class="active"><?php echo $controllerName?></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php
}