<div class="fixed-footer">
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3 col-xs-12">
                    <div class="footer_block">
                        <a href="<?php echo $this->url("index")?>" class="f_logo"><img src="<?php echo $this->basepath('images/logo.png');?>" class="img-responsive" alt="logo"></a>
                        <p> Morganread is commited for jobseekers to have the best opportunities as per their experience <br>
                            And for Employers Morganread  is commited to provide best candidates for  as per their requirement .
                        </p>
                        <div class="social-bar">
                            <ul>
                                <li>
                                    <a class="fa fa-twitter" href="#"></a>
                                </li>
                                <li>
                                    <a class="fa fa-pinterest" href="#"></a>
                                </li>
                                <li>
                                    <a class="fa fa-facebook" href="#"></a>
                                </li>
                                <li>
                                    <a class="fa fa-behance" href="#"></a>
                                </li>
                                <li>
                                    <a class="fa fa-instagram" href="#"></a>
                                </li>
                                <li>
                                    <a class="fa fa-linkedin" href="#"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-2 col-xs-12">
                    <div class="footer_block">
                        <h4>Hot Links</h4>
                        <ul class="footer-links">
                            <li> <a href="<?php echo $this->url("index",array("controller"=>"index","action"=>"index"))?>">Home</a> </li>
                            <li> <a href="<?php echo $this->url("pages",array("controller"=>"index","action"=>"index","id"=>4))?>">About Us</a> </li>
                            <li> <a href="<?php echo $this->url("pages",array("controller"=>"index","action"=>"index","id"=>1))?>">Privacy</a> </li>
                            <li> <a href="<?php echo $this->url("pages",array("controller"=>"index","action"=>"index","id"=>3))?>">Contact Us</a> </li>
                            <li> <a href="<?php echo $this->url("pages",array("controller"=>"index","action"=>"index","id"=>2))?>">Term & Conditions</a> </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4 col-xs-12">
                    <div class="footer_block dark_gry">
                        <h4>Recent Posts</h4>
                       <!-- <ul class="recentpost">
                            <li> <span><a class="plus" href="#"><img src="<?php echo $this->basepath('images/footer/1.png');?>'" alt="" /><i>+</i></a></span>
                                <p><a href="#">Fusce gravida tortor felis, ac dictum risus sagittis</a></p>
                                <h3>Sep 15, 2016</h3>
                            </li>
                            <li> <span><a class="plus" href="#"><img src="<?php echo $this->basepath('images/footer/2.png')?>" alt="" /><i>+</i></a></span>
                                <p><a href="#">Fusce gravida tortor felis, ac dictum risus sagittis</a></p>
                                <h3>Fab 10, 2016</h3>
                            </li>
                            <li> <span><a class="plus" href="#"><img src="<?php echo $this->basepath('images/footer/3.png');?>" alt="" /><i>+</i></a></span>
                                <p><a href="#">Fusce gravida tortor felis, ac dictum risus sagittis</a></p>
                                <h3>Fab 10, 2016</h3>
                            </li>
                        </ul>  --->
                    </div>
                </div>
                <div class="col-sm-6 col-md-3 col-xs-12">
                    <div class="footer_block">
                        <h4>Contact Information</h4>
                        <ul class="personal-info">
                            <li><i class="fa fa-map-marker"></i> A3 Janta TV Tower 40 DLF Kirti Nagar New Delhi - 110015 </li>
                            <li><i class="fa fa-envelope"></i> info@morganread.com</li>
                            <li><i class="fa fa-phone"></i> 011-65008054 </li>
                            <li><i class="fa fa-clock-o"></i> Mon - Sun: 8:00 - 18:00</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <section class="footer-bottom-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="footer-bottom">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">

                            </div>
                            <div class="col-md-12 col-sm-12 col-xs-12 hidden-xs hidden-sm">
                               <!-- <ul class="footer-menu">
                                    <li> <a href="#">Jobs in australia</a> </li>
                                    <li> <a href="#">Jobs in malaysia</a> </li>
                                    <li> <a href="#">Jobs in england</a> </li>
                                    <li> <a href="#">Jobs in saudi arabia</a> </li>
                                    <li> <a href="#">Jobs in south africa</a> </li>
                                    <li> <a href="#">Jobs in saudi Pakistan</a> </li>
                                </ul>  -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <a href="#" class="scrollup"><i class="fa fa-chevron-up"></i></a>