<div class="header-top clear">
    <div class="container">
        <div class="row">
            <div class="col-md-7 hidden-sm hidden-xs">
                <div class="header-top-left header-top-info">
                    <p><a href="tel:+3211234567"><i class="fa fa-phone"></i>+932.123.4567</a></p>
                    <p><a href="mailto:contact@scriptsbundle.com"><i class="fa fa-envelope"></i>contact@scriptsbundle.com</a></p>
                </div>
            </div>
            <div class="col-md-5">
                <div class="header-top-right pull-right header-top-info">
                    <p><a href="#"><i class="fa fa-lock"></i>Login / Register</a></p>
                </div>
            </div>
        </div>
    </div>
</div>