<div class="header-top clear">
    <div class="container">
        <div class="row">
            <div class="col-md-7 hidden-sm hidden-xs">
                <div class="header-top-left header-top-info">
                    <p><a href="tel:+3211234567"><i class="fa fa-phone"></i>+91-8826386237</a></p>
                    <p><a href="mailto:info@jobprofiler.in"><i class="fa fa-envelope"></i>info@morganread.com</a></p>
                </div>
            </div>
            <div class="col-md-5">
                <div class="header-top-right pull-right header-top-info">
                    <p><a href="<?php echo $this->url("register",array("action"=>"login")) ?>"><i class="fa fa-lock"></i> Login </a> / <a href="<?php echo $this->url("register",array("action"=>"index")) ?>"> Register</a></p>
                </div>
            </div>
        </div>
    </div>
</div>