<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="ScriptsBundle">
    <title>Opportunities A Mega Job Board Template</title>

    <!-- =-=-=-=-=-=-= Favicons Icon =-=-=-=-=-=-= -->
    <link rel="icon" href="<?php echo $this->basepath('images/favicon.ico');?>" type="image/x-icon" />

    <!-- =-=-=-=-=-=-= Mobile Specific =-=-=-=-=-=-= -->
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    <!-- BOOTSTRAPE STYLESHEET CSS FILES -->
    <link rel="stylesheet" href="<?php echo $this->basepath('css/bootstrap.min.css');?>">

    <!-- JQUERY SELECT -->
    <link rel="stylesheet" href="<?php echo $this->basepath('css/select2.min.css');?>" />

    <!-- JQUERY MENU -->
    <link rel="stylesheet" href="<?php echo $this->basepath('css/mega_menu.min.css');?>">

    <!-- ANIMATION -->
    <link rel="stylesheet" href="<?php echo $this->basepath('css/animate.min.css');?>">

    <!-- OWl  CAROUSEL-->
    <link rel="stylesheet" href="<?php echo $this->basepath('css/owl.carousel.css');?>">
    <link rel="stylesheet" href="<?php echo $this->basepath('css/owl.style.css');?>">

    <!-- TEMPLATE CORE CSS -->
    <link rel="stylesheet" href="<?php echo $this->basepath('css/style.css');?>">

    <!-- FONT AWESOME -->
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basepath('css/font-awesome.min.css');?>">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basepath('fonts/css/font-awesome.css');?>">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basepath('fonts/css/font-awesome.min.css');?>">
    <link rel="stylesheet" href="<?php echo $this->basepath('css/et-line-fonts.css')?>" type="text/css">

    <!-- Google Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,900" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet" type="text/css">

    <!-- JavaScripts -->
    <script src="<?php echo $this->basepath('js/modernizr.js');?>"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="page">
    <?php

   echo  $this->render('layout/header.phtml');
   echo  $this->render('layout/menu.phtml');
   echo  $this->content;
   echo  $this->render('layout/footer.phtml');
   echo  $this->render('layout/scripts.phtml');

    ?>


</div>
</body>
</html>