<nav id="menu-1" class="mega-menu fa-change-black" data-color="">
    <section class="menu-list-items container">
        <div class="container">
            <ul class="menu-logo">
                <li>
                    <a href="<?php echo $this->url("index")?>"> <img src="<?php echo $this->basepath('images/logo.png');?>" alt="logo" class="img-responsive"> </a>
                </li>
            </ul>
             <ul class="menu-links pull-left" style="margin-left: 15em;">
                <li> <a href="<?php echo $this->url("index")?>"> Home <i class="fa fa-angle-down fa-indicator"></i></a>

                </li>

                 <li><a href="<?php echo $this->url("service")?>"> Services <i class="fa fa-angle-down fa-indicator"></i></a>

                     <?php
                    // var_dump($serviceMenu->current()); exit;
                     ?>
                     <ul class="drop-down-multilevel">

                         <?php

                         foreach ($serviceMenu as $service ){
                             ?>
                             <li>
                                 <a href="<?php echo $this->url("service",array("id"=>$service['serviceId']))?>"> <i class="fa fa-forumbee"></i> <?php echo ucfirst($service['serviceTitle'])?> </a>
                             </li>


                         <?php
                         }
                         ?>

                     </ul>

                 </li>



            </ul>
        </div>
    </section>
</nav>
<div class="clearfix"></div>