<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Change Your Password
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> Change Your Password
            </li>
        </ol>

        <div class="row">
            <div class="col-lg-12">

            <?php
                if(isset($result['status'])){
                    if($result['status']=="fail") {
                        ?>
                        <div class="alert alert-danger">
                            <strong>Error!</strong> <?php echo $result['msg'] ?>
                        </div>
                        <?php

                    }

                    if($result['status']=="success") {
                        ?>
                        <div class="alert alert-success">
                            <strong>Success!</strong> <?php echo $result['msg'] ?>
                        </div>
                        <?php

                    }


                }
            ?>

        </div>



            <?php
            //$det =  $this->empDetails;
            // var_dump($name); exit;

            if (isset($result)) {
            //var_dump($result['fail']); exit;
            if ($result['success'] != "") {
                ?>
                <div class="alert alert-success">
                    <strong>Success!</strong> <?php echo $result['success'] ?>
                </div>

                <?php
            }
            if (is_array($result['fail'])) {
            ?>
            <div class="alert alert-danger">
                <strong>Error!</strong>
                <?php if (is_array($result['fail'])) {
                    ?>
                    <ul>
                        <?php
                        foreach ($result['fail'] as $msg) {
                            echo "<li>" . $msg . "</li>";
                        }
                        ?>
                    </ul>
                    <?php
                }
                }

                if($result['fail']!="")
                {
                    ?>
                    <div class="alert alert-danger">
                        <strong>Error!</strong>
                        <?php
                        echo (!is_array($result['fail']))? $result['fail']:"";

                        ?>
                    </div>

                    <?php
                }





                ?>




                <?php

                }
                ?>
            </div>


        </div>

    </div>
</div>
<!-- /.row -->


<div class="row">
    <div class="col-lg-12 col-md-6">

        <form role="form" method="post" id="addSaleForm"
              action="<?php echo $this->url("sales", array("controller" => "index", "action" => "changepassword")) ?>">

            <div class="col-lg-12">
                <div class="col-lg-12">

                    <div class="form-group">
                        <label>Current Password</label>
                        <input class="form-control" type="text" placeholder="Current Password " name="currpwd"
                               required="required">
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        <label>New Password</label>
                        <input class="form-control" type="text" placeholder="Enter New Password" name="newpwd"
                               required="required">
                    </div>
                </div>

                <div class="col-lg-12">
                    <div class="form-group">
                        <label>Confirm Password</label>
                        <input class="form-control" type="text" placeholder=" Confirm New Password" name="conpwd"
                               required="required">
                    </div>
                </div>



                <div class="col-lg-12">

                    <div class="form-group">
                        <input type="submit" value="Change Password" class="btn btn-primary">
                    </div>
                </div>


            </div>


        </form>


    </div>


</div>
<!-- /.row -->


