<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Sales
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> All Sales



                    <div class="form-group" style="float:right; margin: -1.9em 2em 0 49em;">
                        <a href="<?php echo $this->url('sales',array("controller"=>"index","action"=>"add"))?>" type="button" class="btn btn-success" style="margin-top:25px; margin-left: 25px; width:18em ;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Add Sale&nbsp;&nbsp;&nbsp;&nbsp;</a>

                    </div>

            </li>
        </ol>
    </div>
</div>
<!-- /.row -->



<div class="row">
    <div class="col-lg-12 col-md-6">

            <form role="form" method="post" id="confirmPaymentForm" action="<?php echo  $this->url("sales",array("controller"=>"index","action"=>"confirm")) ?>">

                <div class="col-lg-3">

                    <div class="form-group">
                        <label>Email</label>
                        <input class="form-control" type="text" placeholder="Search with Email" name="email">
                    </div>
                </div>

                <div class="col-lg-3">

                    <div class="form-group">
                        <label>Mobile</label>
                        <input class="form-control" type="text" placeholder="Search with Mobile" id="mobile">

                    </div>
                </div>


                <div class="col-lg-3">

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary" style="margin-top:25px; margin-left: 25px; width:18em ;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Search&nbsp;&nbsp;&nbsp;&nbsp;</button>

                    </div>
                </div>

              <!--  <div class="col-lg-3">

                    <div class="form-group">
                        <a href="<?php echo $this->url('sales',array("controller"=>"index","action"=>"add"))?>" type="button" class="btn btn-success" style="margin-top:25px; margin-left: 25px; width:18em ;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Add Sale&nbsp;&nbsp;&nbsp;&nbsp;</a>

                    </div>
                </div> -->

            </form>


    </div>



</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Sale Search List </h3>
            </div>


                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Amount</th>
                            <!--<th>Mobile</th>-->
                            <th>Date Time </th>
                            <th>Fresh / Upsale</th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php
                        //echo "<pre>";
                         // var_dump(count($paginator->getTotalItemCount())); exit;
                        if($count>0) {
                            foreach ($paginator as $res) {
                                //echo "<pre>";
                                //var_dump($res); exit;
                                ?>

                                <tr class="active">
                                    <td><?php echo $res->custName?></td>
                                    <td><?php echo $res->amount?></td>
                                    <td><?php echo date("d-m-Y H:i:s",strtotime($res->dateAdded)) ?></td>
                                    <td><?php echo ($res->isFresh==1)?"Fresh":"Upsale"?></td>

                                </tr>


                                <?php
                            }
                        } else { ?>

                            <tr class="active">
                                <td colspan="5">Nothing Found</td>

                            </tr>

                            <?php
                        }

                        ?>


                        </tbody>
                    </table>

                    <div class="row">
                        <?php
                        // add at the end of the file after the table
                        echo $this->paginationControl(
                        // the paginator object
                            $this->paginator,
                            // the scrolling style
                            'sliding',
                            // the partial to use to render the control
                            'partial/page.phtml',
                            // the route to link to when a user clicks a control link
                            array(
                               // 'route' => 'sales'
                            )
                        );
                        ?>

                    </div>


        </div>
    </div>
</div>
<!-- /.row -->

