<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Roles
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> All Roles
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->



<div class="row">
    <div class="col-lg-12 col-md-6">

        <form role="form" method="post" id="confirmPaymentForm" action="<?php echo  $this->url("sales",array("controller"=>"index","action"=>"confirm")) ?>">

            <div class="col-lg-10">

                <div class="form-group">
                    <label>Role Name</label>
                    <input class="form-control" type="text" placeholder="Customer Name " name="custName">
                </div>
                <div class="form-group">
                    <label>Customer Email</label>
                    <input class="form-control" type="text" placeholder="Customer Email " name="custEmail">
                </div>

                <div class="form-group">
                    <label>Customer Mobile</label>
                    <input class="form-control" type="text" placeholder="Customer Name " name="custMobile">
                </div>

                <div class="form-group">
                    <label>Amount</label>
                    <input class="form-control" type="text" placeholder="Amount " name="amount">
                </div>

                <div class="form-group">
                    <label>Service Enrolled </label>
                    <select class="form-control" name="services[]" multiple="multiple" id="services">
                        <option value=""> Select Services</option>
                        <?php
                        foreach ($services as $service){
                            ?>
                            <option value="<?php echo $service['id'] ?>"> <?php echo ucfirst($service['name'])?></option>
                        <?php
                        }
                        ?>

                    </select>


                </div>

                <div class="form-group">
                    <label>Agent</label>
                    <input class="form-control" type="text" placeholder="Amount " name="Agent">
                </div>





            </div>



        </form>


    </div>



</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Sale Search List </h3>
            </div>


            <div class="table-responsive">
                <table class="table table-bordered table-hover table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Mobile</th>
                        <th>Date Time </th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php
                    // if($result->count() > 0) {
                    foreach ($result as $res) {
                        var_dump($res); exit;
                        ?>

                        <tr class="active">
                            <td>Atul Walkar</td>
                            <td>shrawan.walkar@gmail.com</td>
                            <td>99225515752 9595674545</td>
                            <td>29/07/2016 <br>30/07/2016</td>
                            <td>Active</td>
                        </tr>


                        <?php
                    }
                    // } else
                    {
                        ?>

                        <tr class="active">
                            <td colspan="5">Nothing Found</td>

                        </tr>

                        <?php
                    }

                    ?>


                    </tbody>
                </table>



            </div>
        </div>
    </div>
    <!-- /.row -->

