<div class="clearfix"></div>
<div class="search">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 nopadding">
                <div class="input-group">
                    <div class="input-group-btn search-panel">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"> <span id="search_concept">Filter By</span> <span class="caret"></span> </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">By Company</a></li>
                            <li><a href="#">By Function</a></li>
                            <li><a href="#">By City </a></li>
                            <li><a href="#">By Salary </a></li>
                            <li><a href="#">By Industry</a></li>
                        </ul>
                    </div>
                    <input type="hidden" name="search_param" value="all" id="search_param">
                    <input type="text" class="form-control search-field" name="x" placeholder="Search term...">
                            <span class="input-group-btn">
                        <button class="btn btn-default" type="button"><span class="fa fa-search"></span></button>
                            </span>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="index5-main-section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12 nopadding">
                <div class="employer-main-section parallex-employer">
                    <h1>Hundreds of users searching for their Dream Job.</h1>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.At vero eos et accusamus et iusto.</p>
                    <a href="post-job.html" class="btn-default">Sign up <i class="fa fa-angle-right"></i> </a>
                </div>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12 nopadding">
                <div class="employee-main-section parallex-employee">
                    <h1>The Easiest way to get your New Dream job.</h1>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.At vero eos et accusamus et iusto.</p>
                    <a href="job-category1.html" class="btn-default">Sign In <i class="fa fa-angle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="light-grey">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="Heading-title black">
                    <h1>Latest Jobs</h1>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium</p>
                </div>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="all-jobs-list-box2">
                    <div class="job-box job-box-2">
                        <div class="col-md-2 col-sm-2 col-xs-12 hidden-sm">
                            <div class="comp-logo">
                                <a href=""><img src="images/company/5.png" class="img-responsive" alt="scriptsbundle"> </a>
                            </div>
                        </div>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <div class="job-title-box">
                                <a href="#">
                                    <div class="job-title"> Technical Documentation Specialist</div>
                                </a> <a href="#"><span class="comp-name">conversi Pvt. Ltd. United States </span></a>
                                <a href="" class="job-type jt-full-time-color"> <i class="fa fa-clock-o"></i> Full time </a>
                            </div>
                            <p>Prompta numquam mel ad, tempor definiebas id usu, cum cu feugiat bonorum. Eu pri labores maiorum patrioque, sea an tation utinam. Idque albucius prodesset ei est, sea te vide contentiones consectetuer.......<a href="">Read More</a> </p>
                        </div>
                        <div class="job-salary"> <i class="fa fa-money"></i> $400 - $500 </div>
                    </div>
                    <div class="job-box job-box-2">
                        <div class="col-md-2 col-sm-2 col-xs-12  hidden-xs hidden-sm">
                            <div class="comp-logo">
                                <a href=""><img src="images/company/1.png" class="img-responsive" alt="scriptsbundle"> </a>
                            </div>
                        </div>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <div class="job-title-box">
                                <a href="#">
                                    <div class="job-title"> Assistant Engineer (IT/Networks)</div>
                                </a> <a href="#"><span class="comp-name">conversi Pvt. Ltd. Malaysia</span></a>
                                <a href="" class="job-type jt-part-time-color"> <i class="fa fa-clock-o"></i> Part Time </a>
                            </div>
                            <p>Prompta numquam mel ad, tempor definiebas id usu, cum cu feugiat bonorum. Eu pri labores maiorum patrioque, sea an tation utinam. Idque albucius prodesset ei est, sea te vide contentiones consectetuer.......<a href="">Read More</a> </p>
                        </div>
                        <div class="job-salary"> <i class="fa fa-money"></i> $200 - $300 </div>
                    </div>
                    <div class="job-box job-box-2">
                        <div class="col-md-2 col-sm-2 col-xs-12  hidden-xs hidden-sm">
                            <div class="comp-logo">
                                <a href=""><img src="images/company/5.png" class="img-responsive" alt="scriptsbundle"> </a>
                            </div>
                        </div>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <div class="job-title-box">
                                <a href="#">
                                    <div class="job-title"> Technical Network Director (IT/Networks)</div>
                                </a> <a href="#"><span class="comp-name">conversi Pvt. Ltd. United States</span></a>
                                <a href="" class="job-type jt-remote-color"> <i class="fa fa-clock-o"></i> Remote </a>
                            </div>
                            <p>Prompta numquam mel ad, tempor definiebas id usu, cum cu feugiat bonorum. Eu pri labores maiorum patrioque, sea an tation utinam. Idque albucius prodesset ei est, sea te vide contentiones consectetuer.......<a href="">Read More</a> </p>
                        </div>
                        <div class="job-salary"> <i class="fa fa-money"></i> $200 - $250 </div>
                    </div>
                    <div class="job-box job-box-2">
                        <div class="col-md-2 col-sm-2 col-xs-12  hidden-xs hidden-sm">
                            <div class="comp-logo">
                                <a href=""><img src="images/company/5.png" class="img-responsive" alt="scriptsbundle"> </a>
                            </div>
                        </div>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <div class="job-title-box">
                                <a href="#">
                                    <div class="job-title"> Technical Documentation Specialist</div>
                                </a> <a href="#"><span class="comp-name">conversi Pvt. Ltd. United States</span></a>
                                <a href="" class="job-type jt-intern-color"> <i class="fa fa-clock-o"></i> Internship </a>
                            </div>
                            <p>Prompta numquam mel ad, tempor definiebas id usu, cum cu feugiat bonorum. Eu pri labores maiorum patrioque, sea an tation utinam. Idque albucius prodesset ei est, sea te vide contentiones consectetuer.......<a href="">Read More</a> </p>
                        </div>
                        <div class="job-salary"> <i class="fa fa-money"></i> $100 - $150 </div>
                    </div>
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="load-more-btn">
                            <button class="btn-default"> View All <i class="fa fa-angle-right"></i> </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="facts">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-3 col-xs-6">
                <div class="fact-box">
                    <div class="single-facts-area">
                        <div class="facts-icon"> <i class="icon-megaphone"></i> </div>
                        <span class="counter">180</span>
                        <h3>Jobs</h3>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 col-xs-6">
                <div class="fact-box">
                    <div class="single-facts-area">
                        <div class="facts-icon"> <i class="icon-document"></i> </div>
                        <span class="counter">175</span>
                        <h3> Resume </h3>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 col-xs-6">
                <div class="fact-box">
                    <div class="single-facts-area">
                        <div class="facts-icon"> <i class="icon-profile-male"></i> </div>
                        <span class="counter">20</span>
                        <h3>Members</h3>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 col-xs-6">
                <div class="fact-box">
                    <div class="single-facts-area">
                        <div class="facts-icon"> <i class="icon-toolbox"></i> </div>
                        <span class="counter">2142</span>
                        <h3>Company</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>